# templates/pv.yaml
{{- if .Values.deployment.persistence.enabled }}
{{- if .Values.deployment.persistence.aws.enabled }}
apiVersion: {{ .Values.k8sKindAPIVersions.persistentVolume }}
kind: PersistentVolume
metadata:
  name: {{ template "..fullname" . }}
  labels:
    purpose: {{ template "..fullname" . }}-identity-server-persistence
  annotations:
    # Add Helm Hooks for PV
    "helm.sh/hook": pre-install,pre-upgrade # Also run on upgrade if needed
    "helm.sh/hook-weight": "-3" # Runs after RBAC (-5), before PVC (-2) and Job (0)
    # Usually you don't want Helm to delete PVs automatically
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  # ... rest of your PV spec ...
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.deployment.persistence.capacity }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.deployment.persistence.aws.volumeHandle }}
{{- end }}
{{- end }}