apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2-identity-server
  labels:
    purpose: wso2-identity-server-identity-server-persistence
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-047d9586e40a8413c
