# templates/pvc.yaml
{{- if .Values.deployment.persistence.enabled }}
{{- if .Values.deployment.persistence.aws.enabled }}
apiVersion: {{ .Values.k8sKindAPIVersions.persistentVolumeClaim }}
kind: PersistentVolumeClaim
metadata:
  name: {{ template "..fullname" . }}
  namespace : {{ .Release.Namespace }}
  annotations:
    # Add Helm Hooks for PVC
    "helm.sh/hook": pre-install,pre-upgrade # Also run on upgrade if needed
    "helm.sh/hook-weight": "-2" # Runs after PV (-3), before Job (0)
    # Usually you don't want Helm to delete PVCs automatically
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  # ... rest of your PVC spec ...
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.deployment.persistence.capacity }}
  selector:
    matchLabels:
      purpose: {{ template "..fullname" . }}-identity-server-persistence
  storageClassName: "" # Correct for static binding
{{- end }}
{{- end }}