apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2-identity-server
  namespace : wso2is
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      purpose: wso2-identity-server-identity-server-persistence
  storageClassName: ""

